deploymentName: "{{deploymentName}}"
vpc: "{{vpc}}"
subnets: "{{subnets}}"
availabilityZones: "{{availabilityZones}}"
adminUsername: "{{adminUsername}}"
sshKey: "{{sshKey}}"
imageName: "{{imageName}}"
instanceType: "{{instanceType}}"
managementGuiPort: "{{managementGuiPort}}"
restrictedSrcAddress: "{{restrictedSrcAddress}}"
ntpServer: "{{ntpServer}}"
bigiqAddress: "{{bigiqAddress}}"
bigiqUsername: "{{bigiqUsername}}"
bigiqPasswordS3Arn: "{{bigiqPasswordS3Arn}}"
bigiqLicensePoolName: "{{bigiqLicensePoolName}}"
bigipElasticLoadBalancer: "{{bigipElasticLoadBalancer}}"
notificationEmail: "{{notificationEmail}}"
appInternalDnsName: "{{appInternalDnsName}}"
applicationPoolTagKey: "{{applicationPoolTagKey}}"
applicationPoolTagValue: "{{applicationPoolTagValue}}"
scalingMinSize: "{{scalingMinSize}}"
scalingMaxSize: "{{scalingMaxSize}}"
costcenter: "{{tag_costcenter}}"
group: "{{tag_group}}"
owner: "{{tag_owner}}"
application: "{{tag_application}}"
environment: "{{tag_environment}}"