---
# iAPP VARS
# SERVICE VARS
service: "www.demo.f5example.com"
service_name: "www_demo_f5example_com"
partition: "Common"
strict_updates: false

vs_address: "0.0.0.0/0"
vs_port: "80"
## SSL CERT 
#client_ssl_cert_name: "{{ service_name }}"
client_ssl_cert_name: "default"

ltm_policy_name: "{{ service_name }}_ltm_policy" 
asm_policy_name: "linux-high"
asm_policy_base64: "{{ lookup('file', 'asm-policy-' + asm_policy_name + '.xml') | b64encode }}"

logging_profile_name: "asm_log_to_splunk"
analytics_profile_name: "my_analytics_profile"
AnalyticsServerIP: "172.16.11.34"
AnalyticsServerPort: "515"


# Pool Vars
applicationPoolTagKey: "aws:autoscaling:groupName"
applicationPoolTagValue: "dev-pm-demo-application-appAutoscaleGroup-J6CION6HARDT"

sd_iApp_service_name: "{{ service_name }}_sd"
sd_iApp_template_name: "f5.service_discovery"
sd_jinja_template_name: "{{ sd_iApp_template_name + '.j2' }}"

# Pool Name ex.
# /Common/www_demo_f5example_com_service_discovery.app/www_demo_f5example_com_service_discovery_pool
application_poolName: "/{{partition}}/{{sd_iApp_service_name}}.app/{{sd_iApp_service_name}}_pool"


# iApp Specific variables
iApp_service_name: "{{ service_name }}"
# TEMPLATE NAME:
iApp_template_name: "f5.http.v1.2.0rc7"
# TEMPLATE TYPE
iApp_template_type: "http_vip_w_waf"
# iApp_template_type: "https_vip_w_waf"
jinja_template_name: "{{ iApp_template_type + '_' + iApp_template_name + '.j2' }}"



